# Generated by Django 2.2.2 on 2020-02-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='minister',
            name='Name',
        ),
    ]
