# Generated by Django 2.2.2 on 2020-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20200222_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DoctorBehaviour',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hygiene',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Nurse',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Pharmacy',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Rating',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='WaitingTime',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
